swagger: '2.0'
info:
  title: MCP Server
  description: MCP Server able to search for products in dataverse.
  version: '1.0'
host: localhost:3001
basePath: /
schemes:
  - http
definitions:
  QueryResponse:
    type: object
    properties:
      jsonrpc:
        type: string
      id:
        type: string
      method:
        type: string
      params:
        type: object
      result:
        type: object
      error:
        type: object
securityDefinitions:
  oauth2-auth:
    type: oauth2
    flow: accessCode
    authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
    tokenUrl: https://login.microsoftonline.com/common/oauth2/token
    scopes:
      https://microsoft.onmicrosoft.com/copilotnonprod/access_as_user: https://microsoft.onmicrosoft.com/copilotnonprod/access_as_user
security:
  - oauth2-auth:
    - https://microsoft.onmicrosoft.com/copilotnonprod/access_as_user
paths:
  /sse:
    get:
      summary: MCP Server able to search for products in dataverse.
      parameters:
        - in: query
          name: sessionId
          type: string
          required: false
      produces:
        - application/json
      responses:
        '200':
          description: Immediate Response
          schema:
            $ref: '#/definitions/QueryResponse'
        '201':
          description: Created and will follow callback
      operationId: ProductSearchMCP
      tags:
        - Agentic
        - McpSse
      security:
        - oauth2-auth: []